version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=dermasmart
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  mongo_data:
